CREATE TABLE `whatsappConfig` (
	`id` int AUTO_INCREMENT NOT NULL,
	`establishmentId` int NOT NULL,
	`subdomain` varchar(100) NOT NULL,
	`token` varchar(500) NOT NULL,
	`status` enum('disconnected','connecting','connected') NOT NULL DEFAULT 'disconnected',
	`connectedPhone` varchar(30),
	`lastQrCode` text,
	`qrCodeExpiresAt` timestamp,
	`notifyOnNewOrder` boolean NOT NULL DEFAULT true,
	`notifyOnPreparing` boolean NOT NULL DEFAULT true,
	`notifyOnReady` boolean NOT NULL DEFAULT true,
	`notifyOnCompleted` boolean NOT NULL DEFAULT false,
	`notifyOnCancelled` boolean NOT NULL DEFAULT true,
	`templateNewOrder` text,
	`templatePreparing` text,
	`templateReady` text,
	`templateCompleted` text,
	`templateCancelled` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `whatsappConfig_id` PRIMARY KEY(`id`),
	CONSTRAINT `whatsappConfig_establishmentId_unique` UNIQUE(`establishmentId`)
);
