CREATE INDEX `idx_aiImageCredits_estId` ON `ai_image_credit_logs` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_botApiKeys_estId` ON `botApiKeys` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_businessHours_estId` ON `businessHours` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_cashbackBal_estId` ON `cashbackBalances` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_cashbackTx_estId` ON `cashbackTransactions` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_cashbackTx_orderId` ON `cashbackTransactions` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_categories_establishmentId` ON `categories` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_collaborators_estId` ON `collaborators` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_comboGroupItems_groupId` ON `comboGroupItems` (`comboGroupId`);--> statement-breakpoint
CREATE INDEX `idx_comboGroups_productId` ON `comboGroups` (`productId`);--> statement-breakpoint
CREATE INDEX `idx_complementGroups_productId` ON `complementGroups` (`productId`);--> statement-breakpoint
CREATE INDEX `idx_complementItems_groupId` ON `complementItems` (`groupId`);--> statement-breakpoint
CREATE INDEX `idx_coupons_establishmentId` ON `coupons` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_coupons_status` ON `coupons` (`status`);--> statement-breakpoint
CREATE INDEX `idx_deliveries_estId` ON `deliveries` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_deliveries_orderId` ON `deliveries` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_deliveries_driverId` ON `deliveries` (`driverId`);--> statement-breakpoint
CREATE INDEX `idx_drivers_establishmentId` ON `drivers` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_establishments_userId` ON `establishments` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_expenseCats_estId` ON `expenseCategories` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_expenses_establishmentId` ON `expenses` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_expenses_categoryId` ON `expenses` (`categoryId`);--> statement-breakpoint
CREATE INDEX `idx_feedbacks_establishmentId` ON `feedbacks` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_feedbacks_status` ON `feedbacks` (`status`);--> statement-breakpoint
CREATE INDEX `idx_financialGoals_estId` ON `financialGoals` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_ifoodConfig_estId` ON `ifoodConfig` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_loyaltyCards_estId` ON `loyaltyCards` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_loyaltyStamps_cardId` ON `loyaltyStamps` (`loyaltyCardId`);--> statement-breakpoint
CREATE INDEX `idx_loyaltyStamps_orderId` ON `loyaltyStamps` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_menuSessions_estId` ON `menu_sessions` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_monthlyGoals_estId` ON `monthlyGoals` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_neighborhoodFees_estId` ON `neighborhoodFees` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_orderItems_orderId` ON `orderItems` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_orderItems_productId` ON `orderItems` (`productId`);--> statement-breakpoint
CREATE INDEX `idx_orders_establishmentId` ON `orders` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_orders_status` ON `orders` (`status`);--> statement-breakpoint
CREATE INDEX `idx_orders_est_status` ON `orders` (`establishmentId`,`status`);--> statement-breakpoint
CREATE INDEX `idx_pdvCustomers_estId` ON `pdv_customers` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_pendingOrders_estId` ON `pending_online_orders` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_pendingOrders_status` ON `pending_online_orders` (`status`);--> statement-breakpoint
CREATE INDEX `idx_printLogs_establishmentId` ON `printLogs` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_printQueue_establishmentId` ON `printQueue` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_printQueue_status` ON `printQueue` (`status`);--> statement-breakpoint
CREATE INDEX `idx_printerSettings_estId` ON `printerSettings` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_printers_establishmentId` ON `printers` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_products_categoryId` ON `products` (`categoryId`);--> statement-breakpoint
CREATE INDEX `idx_products_establishmentId` ON `products` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_products_printerId` ON `products` (`printerId`);--> statement-breakpoint
CREATE INDEX `idx_products_status` ON `products` (`status`);--> statement-breakpoint
CREATE INDEX `idx_pushSubs_establishmentId` ON `pushSubscriptions` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_pushSubs_userId` ON `pushSubscriptions` (`userId`);--> statement-breakpoint
CREATE INDEX `idx_recurringExpHist_expId` ON `recurringExpenseHistory` (`recurringExpenseId`);--> statement-breakpoint
CREATE INDEX `idx_recurringExp_estId` ON `recurringExpenses` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_reviews_establishmentId` ON `reviews` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_reviews_orderId` ON `reviews` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_schedCampaigns_estId` ON `scheduled_campaigns` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_schedCampaigns_status` ON `scheduled_campaigns` (`status`);--> statement-breakpoint
CREATE INDEX `idx_smsBalance_estId` ON `sms_balance` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_smsTx_establishmentId` ON `sms_transactions` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_stockItems_establishmentId` ON `stockItems` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_stockItems_categoryId` ON `stockItems` (`categoryId`);--> statement-breakpoint
CREATE INDEX `idx_stockMovements_stockItemId` ON `stockMovements` (`stockItemId`);--> statement-breakpoint
CREATE INDEX `idx_stockMovements_orderId` ON `stockMovements` (`orderId`);--> statement-breakpoint
CREATE INDEX `idx_stories_establishmentId` ON `stories` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_storyEvents_storyId` ON `storyEvents` (`storyId`);--> statement-breakpoint
CREATE INDEX `idx_storyEvents_estId` ON `storyEvents` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_storyViews_storyId` ON `storyViews` (`storyId`);--> statement-breakpoint
CREATE INDEX `idx_tabItems_tabId` ON `tabItems` (`tabId`);--> statement-breakpoint
CREATE INDEX `idx_tabPayments_tabId` ON `tabPayments` (`tabId`);--> statement-breakpoint
CREATE INDEX `idx_tableSpaces_estId` ON `tableSpaces` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_tables_establishmentId` ON `tables` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_tables_spaceId` ON `tables` (`spaceId`);--> statement-breakpoint
CREATE INDEX `idx_tables_status` ON `tables` (`status`);--> statement-breakpoint
CREATE INDEX `idx_tabs_establishmentId` ON `tabs` (`establishmentId`);--> statement-breakpoint
CREATE INDEX `idx_tabs_tableId` ON `tabs` (`tableId`);--> statement-breakpoint
CREATE INDEX `idx_tabs_status` ON `tabs` (`status`);--> statement-breakpoint
CREATE INDEX `idx_whatsappConfig_estId` ON `whatsappConfig` (`establishmentId`);